[general]
import = [
  "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
  # "~/.config/alacritty/themes/themes/one_dark.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }
# dynamic_padding = true
# opacity = 0.8
# blur = true

[scrolling]
history = 100000
multiplier = 5

[font]
# normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular"}
normal = { family = "MesloLGS NF"}
size = 8

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
